# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
@pytest.mark.selenium


class TestAddactivities():

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
        self.wait = WebDriverWait(self.driver, 10)

    def teardown_method(self, method):
        self.driver.quit()

    def test_addactivities(self):
        self.driver.get("http://127.0.0.1:5000/")
        # wait for login inputs to be present
        username_el = self.wait.until(EC.element_to_be_clickable((By.ID, "login-username")))
        password_el = self.wait.until(EC.element_to_be_clickable((By.ID, "login-password")))
        submit_el = self.wait.until(EC.element_to_be_clickable((By.ID, "login-submit")))
        username_el.click()
        username_el.send_keys("demo")
        password_el.send_keys("demo")
        submit_el.click()
        # wait for and click "Workouts" link
        workouts_link = self.wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "Workouts")))
        workouts_link.click()
        self.driver.find_element(By.ID, "workout-form-date").click()
        self.driver.find_element(By.ID, "workout-form-date").send_keys("2025-05-15")
        self.driver.find_element(By.ID, "workout-form-duration").click()
        self.driver.find_element(By.ID, "workout-form-duration").send_keys("60")
        self.driver.find_element(By.ID, "workout-form-calories").click()
        self.driver.find_element(By.ID, "workout-form-calories").send_keys("500")
        self.driver.find_element(By.ID, "workout-form-notes").click()
        self.driver.find_element(By.ID, "workout-form-notes").send_keys("feel good")
        self.driver.find_element(By.ID, "workout-add").click()
        self.driver.find_element(By.LINK_TEXT, "Analytics").click()