# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pytest

@pytest.mark.selenium

class TestViewleaderboard():

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
        self.wait = WebDriverWait(self.driver, 10)

    def teardown_method(self, method):
        self.driver.quit()

    def test_viewleaderboard(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.find_element(By.ID, "login-username").click()
        self.driver.find_element(By.ID, "login-username").send_keys("demo")
        self.driver.find_element(By.ID, "login-password").send_keys("demo")
        self.driver.find_element(By.ID, "login-submit").click()
        self.driver.find_element(By.LINK_TEXT, "Leader Board").click()
        # wait for leaderboard table to appear and verify
        #leaderboard = self.wait.until(EC.presence_of_element_located((By.ID, "leaderboard-table")))
        #assert leaderboard is not None, "Leaderboard table not found"
