# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestRegisterlogin():

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_registerlogin(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.find_element(By.CSS_SELECTOR, ".text-center > .text-success").click()
        self.driver.find_element(By.ID, "register-username").click()
        self.driver.find_element(By.ID, "register-username").send_keys("demo")
        self.driver.find_element(By.ID, "register-password").send_keys("demo")
        self.driver.find_element(By.ID, "register-submit").click()

        # wait for login inputs to be clickable
        username_el = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.ID, "login-username"))
        )
        password_el = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.ID, "login-password"))
        )
        submit_el = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.ID, "login-submit"))
        )
        username_el.click()
        username_el.clear()
        username_el.send_keys("demo")
        password_el.click()
        password_el.clear()
        password_el.send_keys("demo")
        submit_el.click()

