# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestNewTest():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_newTest(self):
        self.driver.get("http://127.0.0.1:5000")
        # click username field
        self.driver.find_element(By.ID, "login-username").click()
        # double click to select existing text
        element = self.driver.find_element(By.ID, "login-username")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # send credentials
        self.driver.find_element(By.ID, "login-username").send_keys("demo")
        self.driver.find_element(By.ID, "login-password").send_keys("demo")
        self.driver.find_element(By.ID, "login-submit").click()
