"""recover some delete fields

Revision ID: 0063773662dd
Revises: 82d0338a8407
Create Date: 2025-05-16 21:35:03.922985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0063773662dd'
down_revision = '82d0338a8407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('private_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    with op.batch_alter_table('shared_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_workout', schema=None) as batch_op:
        batch_op.drop_column('shared_at')

    with op.batch_alter_table('private_message', schema=None) as batch_op:
        batch_op.drop_column('is_read')
        batch_op.drop_column('sent_at')
        batch_op.drop_column('content')

    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
