"""modify share workout model

Revision ID: 10a920caf435
Revises: 
Create Date: 2025-05-16 21:32:11.768577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a920caf435'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_workout', schema=None) as batch_op:
        batch_op.drop_column('shared_at')

    with op.batch_alter_table('weight_record', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_record', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('shared_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
