"""delete unused message fields

Revision ID: 82d0338a8407
Revises: bf609f51f2df
Create Date: 2025-05-16 21:34:13.861629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d0338a8407'
down_revision = 'bf609f51f2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_message', schema=None) as batch_op:
        batch_op.drop_column('sent_at')
        batch_op.drop_column('content')
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('sent_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
